# Develop environment setup
spring:
    application:
        name: "Help Desk Tickets - Development"

# Develop database connections
    
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                formatSql: true
                jdbc:
                    lob:
                        non-contextual-creation: true
        show-sql: true
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    sql:
        init:
            mode: always
    datasource:
        url: "jdbc:postgresql://localhost:5432/mydatabase"
        username: myuser
        password: secret

# LDAP Setup
    ldap:
        urls: "ldap://10.10.50.3:389"
        username: "cn={0},dc=local,dc=metrotelecom,dc=com,dc=br"
        base: "ou=users,ou=system,ou=admin"
        userDnPatterns: "uid={0},ou=users"

    main:
        allow-bean-definition-overriding: TRUE

    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER

server:
    servlet:
        context-path: '/hdesktickets'
logging:
    level:
        org:
            springframework:
                security: 'DEBUG'

# keys
jwt:
    public:
        key: 'classpath:static/key/pub.key'
    private:
        key: 'classpath:static/key/app.key'
    secret: 7CA6AFDA-B94C-4CCF-AC45-7C802BD0745F

