# Develop environment setup
spring:
    application:
        name: "Help Desk Tickets - Development"
    main:
        allow-bean-definition-overriding: true
# Develop database connections
    
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                formatSql: true
                jdbc:
                    lob:
                        non-contextual-creation: true
        show-sql: true
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    sql:
        init:
            mode: always
    datasource:
        url: "jdbc:postgresql://localhost:5432/mydatabase"
        username: myuser
        password: secret

    mail:
        host: smtp.doubletelecom.com.br
        port: 587
        username: ti@doubletelecom.com.br
        password: "123456"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    servlet:
        context-path: '/hdesktickets'
logging:
    level:
        org:
            springframework:
                security: 'DEBUG'

# keys
jwt:
    public:
        key: 'classpath:static/key/pub.key'
    private:
        key: 'classpath:static/key/app.key'

