# Production environment setup
spring:
    application:
        name: "Help Desk Tickets - API"
   
    # Production database connections
    jpa:
        properties:
            hibernate:
                formatSql: false
        show-sql: false
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    sql:
        init:
            mode: always
    datasource:
        url: "jdbc:postgresql://${DATASOURCE_URL:localhost:5433/hdesktickets_db_dev}"
        username: ${DATASOURCE_USERNAME:hdesktickets}
        password: ${DATASOURCE_PASSWORD:secret}

server:
    port: ${HDT_PORT:8080}
    error:
        include-stacktrace: never

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        disable-swagger-default-url: true
        #For sorting endpoints alphabetically
        operationsSorter: alpha
        #For sorting tags alphabetically
        tagsSorter: alpha
    api-docs:
        path: /v3/api-docs
        
# keys
jwt:
    public:
        key: ${HDT_API_RSA_PUBLIC_KEY:classpath:dev_keys/public.key}
    private:
        key: ${HDT_API_RSA_PRIVATE_KEY:classpath:dev_keys/private.key}
    token:
        ttl:
            access: ${HDT_API_TOKEN_ACCESS_TTL:60}
            refresh: ${HDT_API_TOKEN_REFRESH_TTL:900}
