# Production environment setup
spring:
    profiles:
        active: ${HDT_API_PROFILE:development}
    application:
        name: "Help Desk Tickets - Production"
server:
    servlet:
        context-path: '/hdesktickets'

