# =============================================================================
# HelpDesk Tickets - Configuração do ambiente: test
# =============================================================================

HDT_PORT='8081'
HDT_DATASOURCE_URL='localhost:5433/hdesktickets_db_test'
HDT_DATASOURCE_USERNAME='hdesktickets'
HDT_DATASOURCE_PASSWORD='secret'
HDT_API_RSA_PUBLIC_KEY='classpath:dev_keys/public.key'
HDT_API_RSA_PRIVATE_KEY='classpath:dev_keys/private.key'
HDT_JAR='target/help_desk_tickets-0.0.1-SNAPSHOT.jar'
HDT_API_TOKEN_ACCESS_TTL='60'
HDT_API_TOKEN_REFRESH_TTL='900'
