# Production environment setup
spring:
    profiles:
        active: development
    application:
        name: "Help Desk Tickets - Production"
server:
    servlet:
        context-path: '/hdesktickets'
logging:
    level:
        org:
            springframework:
                security: 'DEBUG'

