# Develop environment setup
spring:
    application:
        name: "Help Desk Tickets - Development"
    #main:
        #allow-bean-definition-overriding: true

    # Develop database connections
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                formatSql: true
                jdbc:
                    lob:
                        non-contextual-creation: true
        show-sql: true
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    sql:
        init:
            mode: always
    datasource:
        url: "jdbc:postgresql://localhost:5433/hdesktickets_db_dev"
        username: hdesktickets
        password: secret

server:
    error:
        include-stacktrace: never
    port: ${HDT_PORT:8080}

logging:
    level:
        org:
            springframework:
                security: 'DEBUG'

springdoc:
    swagger-ui:
        enabled: true
        #For sorting endpoints alphabetically
        operationsSorter: alpha
        #For sorting tags alphabetically
        tagsSorter: alpha
        
# keys
jwt:
    public:
        key: ${HDT_API_RSA_PUBLIC_KEY:classpath:dev_keys/public.key}
    private:
        key: ${HDT_API_RSA_PRIVATE_KEY:classpath:dev_keys/private.key}
